//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novice_Motorist.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_Info
    {
        public int Id { get; set; }
        public string Additional_Option { get; set; }
        public string Quantity_place { get; set; }
        public string Payload_Capacity { get; set; }
        public int Id_Cars { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
